### ISSUE TITLE
Connection to Serverless cluster failing

### ISSUE THREAD

**Issue by pvantilb** [lapaygroup/doctrine-cockroachdb#6]
Attempting to use this to connect to a serverless cluster but am only getting a PDOException Error stating that it is missing a connection parameter of "cluster". Have tried both with DBAL style yaml value definition as well as using the plain url value in the DBAL connection yaml value.

Not sure if I am doing something wrong or if this doesn't support serverless clusters.

**Comment by iamwildtuna** [comment]
Hello! What kind of serverless connection? What does the connection string look like in it? I don't see any information about the cluster parameter in their documentation https://www.cockroachlabs.com/docs/stable/build-a-php-app-with-cockroachdb.html

**Comment by iamwildtuna** [comment]
I made a serverless test bench and was able connected to the database by specifying the cluster in the database name.

Connection URL format: //clouduser:cloudpass@free-tier7.aws-eu-west-1.cockroachlabs.cloud:26257/clustername.dbname
Example: //wildtuna:password@free-tier7.aws-eu-west-1.cockroachlabs.cloud:26257/lapaygroup-test-869.defaultdb

doctrine configuration exsmple:
```yaml
doctrine:
  dbal:
    url: '//wildtuna:password@free-tier7.aws-eu-west-1.cockroachlabs.cloud:26257/lapaygroup-test-869.defaultdb'
    platform_service: LapayGroup\DoctrineCockroach\Platforms\CockroachPlatform
    driver_class: LapayGroup\DoctrineCockroach\Driver\CockroachDriver
```

```yaml
doctrine:
  dbal:
    user: wildtuna
    password: password
    port: 26257
    host: free-tier7.aws-eu-west-1.cockroachlabs.cloud
    dbname: lapaygroup-test-869.defaultdb
    platform_service: LapayGroup\DoctrineCockroach\Platforms\CockroachPlatform
    driver_class: LapayGroup\DoctrineCockroach\Driver\CockroachDriver
```
