### ISSUE TITLE
Can't connect to serverless CockroachDB instance

### ISSUE THREAD

**Issue by gitknul** [lapaygroup/doctrine-cockroachdb#7]
I am not able to connect to my serverless CockroachDB instance. I can connect using the `cockroach sql` command.

Here is my Doctrine configuration, derived from the README:

```yaml
doctrine:
    dbal:
        user: olivier
        password: *redacted*
        port: 26257
        host: free-tier4.aws-us-west-2.cockroachlabs.cloud
        dbname: bouchoms-coco-dev-2076.defaultdb

        platform_service: LapayGroup\DoctrineCockroach\Platforms\CockroachPlatform
        driver_class: LapayGroup\DoctrineCockroach\Driver\CockroachDriver

        sslmode: verify-full
        sslrootcert: crdb.crt
```

Output from `bin/console doctrine:database:create`:

```

In AbstractPostgreSQLDriver.php line 88:
                                                                                                                                                                                                                                              
  An exception occurred in driver: SQLSTATE[08006] [7] connection to server at "free-tier4.aws-us-west-2.cockroachlabs.cloud" (54.200.127.45), port 26257 failed: FATAL:  codeParamsRoutingFailed: missing cluster name in connection string  
                                                                                                                                                                                                                                              

In Exception.php line 18:
                                                                                                                                                                                                             
  SQLSTATE[08006] [7] connection to server at "free-tier4.aws-us-west-2.cockroachlabs.cloud" (54.200.127.45), port 26257 failed: FATAL:  codeParamsRoutingFailed: missing cluster name in connection string  
                                                                                                                                                                                                             

In PDOConnection.php line 40:
                                                                                                                                                                                                             
  SQLSTATE[08006] [7] connection to server at "free-tier4.aws-us-west-2.cockroachlabs.cloud" (54.200.127.45), port 26257 failed: FATAL:  codeParamsRoutingFailed: missing cluster name in connection string  
                                                                                                                                                                                                             

doctrine:database:create [-s|--shard SHARD] [-c|--connection [CONNECTION]] [--if-not-exists]
```

Do you have any idea how I can connect to my CockroachDB serverless instance?

**Comment by iamwildtuna** [comment]
Hi! Very strange, I have no problems. Try url style connection string.

**Comment by gitknul** [comment]
Hi, thank you for your quick reply. When I use the url parameter I experience the same problem and get the same error.

```
doctrine:
    dbal:
        url: '//olivier:password@free-tier4.aws-us-west-2.cockroachlabs.cloud:26257/bouchoms-coco-dev-2076.defaultdb'

        platform_service: LapayGroup\DoctrineCockroach\Platforms\CockroachPlatform
        driver_class: LapayGroup\DoctrineCockroach\Driver\CockroachDriver

        sslmode: verify-full
        sslrootcert: crdb.crt
```
