### ISSUE TITLE
Is ths still mantained?

### ISSUE THREAD

**Issue by Paillat-dev** [lapaygroup/doctrine-cockroachdb#9]

**Comment by iamwildtuna** [comment]
Overall, this driver doesn't make much sense. It is enough just to correctly register the mapping in the doctrine config.

Example doctrine.yaml:
```yaml
doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    mapping_types:
      int8: integer
      _int8: integer
      int2vector: array
      _text: string
      name: string
```

If you have a specific problem, write it down.
